name: Deploy to pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up bun
      uses: oven-sh/setup-bun@v2

    - name: Commit report
      run: |
         git config --global user.name 'github-actions'
         git config --global user.email 'github-actions@github.com'

    - name: Run deploy script
      run: |
         export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
         bun install
         bun run deploy
